# -*- coding: utf-8 -*-
"""Alok Sales lead Gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbzGcSlX-jzwL_CLKTE_nqlFTypZ6sW0
"""

!mkdir -p b2b_lead_engine/data
!mkdir -p b2b_lead_engine/app

!pip install pandas email-validator

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/data/companies.csv
# company_id,name,domain,industry,location,employee_size,company_type
# 1,Acme Corp,acme.com,SaaS,India,120,Startup
# 2,Foo Technologies,foo.com,FinTech,US,300,Enterprise
# 3,Bar Systems,bar.com,SaaS,India,80,Startup
# 4,Baz Solutions,baz.com,SaaS,India,600,Enterprise
# 5,NovaSoft,novasoft.com,SaaS,India,200,Startup

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/data/contacts.csv
# contact_id,company_id,full_name,job_title,email,company_domain
# 1,1,Rahul Sharma,VP Sales,rahul@acme.com,acme.com
# 2,1,Anita Verma,CEO,anita@acme.com,acme.com
# 3,2,John Smith,Director Growth,john@foo.com,foo.com
# 4,3,Pooja Mehta,Head of Partnerships,pooja@bar.com,bar.com
# 5,3,Pooja Mehta,Head of Partnerships,pooja@bar.com,bar.com
# 6,4,Arjun Malhotra,CFO,arjun@baz.com,baz.com
# 7,5,Neha Kapoor,Founder,neha@novasoft.com,novasoft.com
# 8,5,Kunal Jain,Sales Head,kunal@novasoft.com,novasoft.com

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/app/icp.py
# class ICP:
#     def __init__(self, industries, locations, emp_min, emp_max, company_type):
#         self.industries = industries
#         self.locations = locations
#         self.emp_min = emp_min
#         self.emp_max = emp_max
#         self.company_type = company_type
# 
#     def matches(self, company):
#         return (
#             company["industry"] in self.industries and
#             company["location"] in self.locations and
#             self.emp_min <= company["employee_size"] <= self.emp_max and
#             company["company_type"] == self.company_type
#         )

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/app/company_filter.py
# import pandas as pd
# 
# def filter_companies(companies_df, icp):
#     matched = []
#     for _, row in companies_df.iterrows():
#         if icp.matches(row):
#             matched.append(row)
#     return pd.DataFrame(matched)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/app/role_normalizer.py
# ROLE_MAP = {
#     "CEO / Founder": ["ceo", "founder"],
#     "Sales Head": ["sales", "growth", "revenue"],
#     "Partnerships Head": ["partnership", "alliances"],
#     "Finance Head": ["finance", "cfo"],
#     "Operations Head": ["operations", "ops"]
# }
# 
# def normalize_role(title):
#     title = title.lower()
#     for role, keywords in ROLE_MAP.items():
#         for k in keywords:
#             if k in title:
#                 return role
#     return "Other"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/app/verifier.py
# from email_validator import validate_email, EmailNotValidError
# 
# DISPOSABLE_DOMAINS = ["mailinator.com", "tempmail.com"]
# 
# def verify_email(email, company_domain):
#     try:
#         validate_email(email)
#         domain = email.split("@")[1]
#         if domain != company_domain:
#             return False
#         if domain in DISPOSABLE_DOMAINS:
#             return False
#         return True
#     except EmailNotValidError:
#         return False

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/app/deduplicator.py
# def deduplicate_contacts(df):
#     df = df.drop_duplicates(subset=["email"])
#     df = df.drop_duplicates(subset=["full_name", "company_domain"])
#     return df

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/app/exporter.py
# from datetime import datetime
# 
# def export_csv(contacts, icp_name):
#     contacts["icp_used"] = icp_name
#     contacts["exported_at"] = datetime.utcnow().isoformat()
#     contacts.to_csv("/content/final_export.csv", index=False)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile b2b_lead_engine/app/main.py
# import pandas as pd
# from icp import ICP
# from company_filter import filter_companies
# from role_normalizer import normalize_role
# from verifier import verify_email
# from deduplicator import deduplicate_contacts
# from exporter import export_csv
# 
# companies = pd.read_csv("/content/b2b_lead_engine/data/companies.csv")
# contacts = pd.read_csv("/content/b2b_lead_engine/data/contacts.csv")
# 
# icp = ICP(
#     industries=["SaaS"],
#     locations=["India"],
#     emp_min=50,
#     emp_max=500,
#     company_type="Startup"
# )
# 
# filtered_companies = filter_companies(companies, icp)
# 
# contacts = contacts[contacts["company_id"].isin(filtered_companies["company_id"])]
# 
# contacts["role_bucket"] = contacts["job_title"].apply(normalize_role)
# contacts["verified"] = contacts.apply(
#     lambda r: verify_email(r["email"], r["company_domain"]),
#     axis=1
# )
# 
# contacts = contacts[contacts["verified"]]
# contacts = deduplicate_contacts(contacts)
# 
# export_csv(contacts, "SaaS_India_Startup")
# print("Export completed: final_export.csv")

!python b2b_lead_engine/app/main.py

from google.colab import files
files.download("/content/final_export.csv")